import type { Metadata } from "next";
import { AdsterraAd } from "@/components/AdsterraAd";
import { CalculatorApp } from "@/components/CalculatorApp";

export const metadata: Metadata = {
  title: "College Acceptance Calculator: Estimate Your Admission Chances",
  description: "Use our free college acceptance calculator to estimate your admission chances using GPA, SAT score, and the college you want to attend.",
  alternates: { canonical: "/calculator" },
};

export default function CalculatorPage() { return <><CalculatorApp/><main className="border-t border-white/10 bg-[#08090d]"><article className="mx-auto max-w-4xl px-5 py-16 text-[1.03rem] leading-8 text-zinc-300 sm:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-lime-300">Free admissions tool</p><h1 className="mt-4 text-4xl font-black tracking-[-.05em] text-white sm:text-5xl">How to use this college acceptance calculator</h1><p className="mt-6 text-xl leading-9 text-zinc-200">Enter your GPA, SAT score, and a college to receive a quick estimate of how your academic profile compares with that school’s planning benchmarks. The result is designed to help you explore and build a balanced list—not predict an admissions decision.</p><AdsterraAd format="native" className="my-10"/>
  <section className="mt-12"><h2 className="text-3xl font-black tracking-tight text-white">What does the calculator measure?</h2><p className="mt-5">The estimate compares two academic inputs with the selected college’s general profile. GPA offers a simplified view of classroom performance, while the SAT adds a standardized reference when the institution considers testing. The calculation also accounts for broad selectivity. It cannot measure course rigor, grade trends, essays, recommendations, activities, major capacity, residency, talent, personal context, or institutional priorities.</p><p className="mt-5">Because those missing factors matter, treat the percentage as a list-building signal. A low estimate can identify a reach worth balancing with other options. A higher estimate can highlight a promising target or likely school, but it never creates a guarantee.</p></section>
  <section className="mt-12"><h2 className="text-3xl font-black tracking-tight text-white">How accurate is a college admission chances calculator?</h2><p className="mt-5">No public calculator can reproduce an admissions committee. Colleges read applications using policies and priorities that vary by institution and year. Published academic ranges describe groups of students, not a formula for individual decisions. Results are most useful when you compare several schools, verify current requirements, and combine the estimate with research about cost and fit.</p><p className="mt-5">For highly selective colleges, nearly every applicant should consider the school a reach even with exceptional grades and scores. For test-blind institutions, SAT results should not influence your real-world admission strategy. Always check the official admissions website before acting on a benchmark.</p></section>
  <section className="mt-12"><h2 className="text-3xl font-black tracking-tight text-white">Turn your result into a balanced list</h2><p className="mt-5">Run the calculator for several colleges and sort them into reach, target, and likely categories. Include multiple schools in every category and make sure each is somewhere you would genuinely attend. Then add affordability: use official net price calculators and identify at least one option that appears both academically and financially dependable.</p><p className="mt-5">Your strongest list creates several good outcomes instead of depending on one percentage. Explore our <a href="/colleges" className="font-bold text-lime-300">college directory</a>, compare schools side by side, or read the guide on <a href="/guides/what-colleges-can-i-get-into" className="font-bold text-lime-300">what colleges you can get into</a>.</p></section>
  <div className="mt-12 rounded-3xl border border-white/10 bg-white/[.03] p-7"><h2 className="text-2xl font-black text-white">Important limitation</h2><p className="mt-3 text-sm leading-6 text-zinc-400">Admitly provides an educational estimate for exploration. It is not affiliated with any university and does not offer an admission guarantee. Verify requirements and deadlines directly with each institution.</p></div>
</article></main></> }
