import { universities } from "@/data/universities";
import { SiteShell } from "@/components/SiteShell";

const features = [
  { n: "01", title: "Explore colleges", copy: "Search schools by location, selectivity, GPA and SAT profile.", href: "/colleges", cta: "Browse directory" },
  { n: "02", title: "Compare your shortlist", copy: "Put two schools side by side and see the differences that matter.", href: "/compare", cta: "Compare schools" },
  { n: "03", title: "Build a smarter plan", copy: "Use focused guides and free tools to turn uncertainty into next steps.", href: "/guides", cta: "Read the guides" },
];

export default function Home() {
  return <SiteShell><main>
    <section className="relative overflow-hidden"><div className="pointer-events-none absolute left-1/2 top-0 h-[40rem] w-[65rem] -translate-x-1/2 rounded-full bg-lime-300/[.07] blur-3xl" /><div className="relative mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
      <div><div className="inline-flex items-center gap-2 rounded-full border border-lime-300/20 bg-lime-300/8 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.18em] text-lime-300"><span className="size-1.5 rounded-full bg-lime-300" /> Your college command center</div><h1 className="mt-7 max-w-4xl text-5xl font-black leading-[.88] tracking-[-.07em] sm:text-7xl">Your future is bigger than an <span className="text-lime-300">acceptance rate.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-zinc-400">Explore colleges, compare your options and get a quick read on where your stats could take you.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/calculator" className="rounded-full bg-lime-300 px-7 py-4 text-center text-sm font-black text-zinc-950">Calculate my chances →</a><a href="/colleges" className="rounded-full border border-white/15 px-7 py-4 text-center text-sm font-black text-white">Explore colleges</a></div><p className="mt-5 text-xs text-zinc-600">Free to use · No sign-up · Built for exploration</p></div>
      <div className="relative mx-auto w-full max-w-lg rotate-1 rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_80%_5%,rgba(190,242,100,.22),transparent_35%),#121319] p-7 shadow-2xl"><div className="flex items-center justify-between text-[10px] font-black uppercase tracking-[.2em]"><span className="text-lime-300">Chance check</span><span className="text-zinc-600">Sample result</span></div><p className="mt-14 text-xs font-bold uppercase tracking-widest text-zinc-500">Your chances at</p><h2 className="mt-2 text-4xl font-black tracking-[-.05em]">UC Davis</h2><div className="my-7 flex items-end gap-4"><span className="text-8xl font-black leading-none tracking-[-.08em] text-lime-300">68%</span><span className="mb-3 rounded-full bg-lime-300/10 px-3 py-1 text-xs font-black text-lime-300">TARGET</span></div><div className="grid grid-cols-2 gap-3 border-t border-white/10 pt-5 text-xs"><p className="text-zinc-500">GPA <strong className="ml-2 text-white">3.82</strong></p><p className="text-zinc-500">SAT <strong className="ml-2 text-white">1390</strong></p></div></div>
    </div></section>
    <section className="border-y border-white/8 bg-white/[.025]"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-white/8 px-5 py-7 text-center sm:px-8 md:grid-cols-4"><div><strong className="block text-2xl font-black">60</strong><span className="text-xs text-zinc-500">college profiles</span></div><div><strong className="block text-2xl font-black">5</strong><span className="text-xs text-zinc-500">free tools</span></div><div className="hidden md:block"><strong className="block text-2xl font-black">0</strong><span className="text-xs text-zinc-500">accounts required</span></div><div className="hidden md:block"><strong className="block text-2xl font-black">30 sec</strong><span className="text-xs text-zinc-500">to a result</span></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><p className="text-xs font-black uppercase tracking-[.22em] text-lime-300">One place. A clearer plan.</p><h2 className="mt-4 max-w-2xl text-4xl font-black tracking-[-.05em] sm:text-5xl">From “what if?” to what’s next.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{features.map((f) => <a href={f.href} key={f.n} className="group rounded-3xl border border-white/10 bg-white/[.035] p-7 transition hover:-translate-y-1 hover:border-lime-300/30"><span className="font-mono text-xs text-lime-300">{f.n}</span><h3 className="mt-12 text-2xl font-black tracking-tight">{f.title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-zinc-400">{f.copy}</p><p className="mt-7 text-sm font-black text-white group-hover:text-lime-300">{f.cta} →</p></a>)}</div></section>
    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.22em] text-lime-300">Popular schools</p><h2 className="mt-3 text-3xl font-black tracking-tight">Start with a dream.</h2></div><a href="/colleges" className="hidden text-sm font-black text-zinc-400 sm:block">View all →</a></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{universities.slice(0, 4).map(u => <a key={u.id} href={`/colleges/${u.id}`} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 hover:bg-white/[.06]"><span className="mb-8 grid size-10 place-items-center rounded-xl text-xs font-black text-zinc-950" style={{backgroundColor:u.accent}}>{u.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><h3 className="font-black">{u.name}</h3><p className="mt-1 text-xs text-zinc-500">{u.location} · {u.acceptanceRate}% admit rate</p></a>)}</div></section>
  </main></SiteShell>;
}
