"use client";
import { useMemo, useState } from "react";
import { universities } from "@/data/universities";

export function CollegeDirectory() {
  const [query, setQuery] = useState("");
  const [type, setType] = useState("All");
  const results = useMemo(() => universities.filter(u => `${u.name} ${u.location}`.toLowerCase().includes(query.toLowerCase()) && (type === "All" || u.type === type)), [query, type]);
  return <><div className="mt-10 flex flex-col gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-3 sm:flex-row"><label className="flex flex-1 items-center gap-3 rounded-xl bg-black/20 px-4"><span aria-hidden>⌕</span><input className="min-h-12 w-full bg-transparent text-sm outline-none placeholder:text-zinc-600" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by college or city..." aria-label="Search colleges" /></label><div className="flex gap-2">{["All","Public","Private"].map(v=><button key={v} onClick={()=>setType(v)} className={`rounded-xl px-4 py-3 text-xs font-black ${type===v?"bg-lime-300 text-zinc-950":"text-zinc-400 hover:bg-white/5"}`}>{v}</button>)}</div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{results.map(u=><article key={u.id} className="rounded-3xl border border-white/10 bg-white/[.03] p-6"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-xl text-sm font-black text-zinc-950" style={{backgroundColor:u.accent}}>{u.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-zinc-500">{u.type}</span></div><h2 className="mt-7 text-xl font-black">{u.name}</h2><p className="mt-1 text-sm text-zinc-500">{u.location}</p><dl className="mt-6 grid grid-cols-3 border-y border-white/8 py-4 text-center"><div><dt className="text-[10px] uppercase text-zinc-600">Admit</dt><dd className="mt-1 text-sm font-black">{u.acceptanceRate}%</dd></div><div><dt className="text-[10px] uppercase text-zinc-600">Avg GPA</dt><dd className="mt-1 text-sm font-black">{u.avgGpa}</dd></div><div><dt className="text-[10px] uppercase text-zinc-600">{u.testBlind?"Testing":"Avg SAT"}</dt><dd className="mt-1 text-sm font-black">{u.testBlind?"Test-free":u.avgSat}</dd></div></dl><a href={`/colleges/${u.id}`} className="mt-5 block rounded-full bg-white/8 px-4 py-3 text-center text-xs font-black transition hover:bg-lime-300 hover:text-zinc-950">View admissions profile →</a></article>)}</div>
    {!results.length && <p className="py-20 text-center text-zinc-500">No colleges match those filters.</p>}</>;
}
