"use client";
import { useState, type ReactNode } from "react";

export function FreeTools(){
 const [gpa,setGpa]=useState("3.7"),[sat,setSat]=useState("1350"),[reach,setReach]=useState("3"),[target,setTarget]=useState("4"),[likely,setLikely]=useState("2");
 const g=Number(gpa),s=Number(sat), total=Number(reach)+Number(target)+Number(likely);
 const satPercentile=s>=1530?"99th":s>=1450?"97th":s>=1350?"91st":s>=1250?"82nd":s>=1150?"67th":"below 67th";
 const balance=Number(likely)>=2&&Number(target)>=3?"Balanced start":"Needs more balance";
 return <div className="mt-10 grid gap-5 lg:grid-cols-2">
  <Tool title="GPA snapshot" label="Put your unweighted GPA in context." badge="ACADEMICS"><label className="text-xs font-bold text-zinc-500">Your GPA (0–4.0)</label><input value={gpa} onChange={e=>setGpa(e.target.value)} type="number" min="0" max="4" step=".01" className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-3xl font-black outline-none focus:border-lime-300/50"/><Result value={g>=3.9?"Exceptional":g>=3.7?"Strong":g>=3.3?"Competitive":"Developing"} copy={g>=3.7?"Your GPA can support a broad college list. Course rigor and context still matter.":"Look for schools whose middle academic range aligns with your record."}/></Tool>
  <Tool title="SAT percentile check" label="See roughly where your score sits nationally." badge="TESTING"><label className="text-xs font-bold text-zinc-500">Your SAT score (400–1600)</label><input value={sat} onChange={e=>setSat(e.target.value)} type="number" min="400" max="1600" step="10" className="mt-2 w-full rounded-2xl border border-white/10 bg-black/20 p-4 text-3xl font-black outline-none focus:border-lime-300/50"/><Result value={satPercentile} copy="Approximate percentile for quick planning. Always compare against each college’s current score range."/></Tool>
  <Tool title="College-list balance" label="Check the shape of your shortlist." badge="STRATEGY"><div className="grid grid-cols-3 gap-3"><NumberBox label="Reach" value={reach} setValue={setReach}/><NumberBox label="Target" value={target} setValue={setTarget}/><NumberBox label="Likely" value={likely} setValue={setLikely}/></div><Result value={balance} copy={`${total || 0} schools total. Aim for choices you would genuinely attend in every category.`}/></Tool>
  <Tool title="Chance calculator" label="Estimate, save and share your result." badge="MOST POPULAR"><div className="mt-2 rounded-2xl bg-lime-300/[.08] p-5"><p className="text-5xl font-black text-lime-300">30 sec</p><p className="mt-2 text-sm leading-6 text-zinc-400">Add your GPA and SAT, choose a college, and get a playful estimate built for exploration.</p></div><a href="/calculator" className="mt-5 block rounded-full bg-lime-300 p-3 text-center text-xs font-black text-zinc-950">Calculate my chances →</a></Tool>
 </div>;
}
function Tool({title,label,badge,children}:{title:string;label:string;badge:string;children:ReactNode}){return <section className="rounded-3xl border border-white/10 bg-white/[.03] p-6 sm:p-8"><p className="text-[10px] font-black tracking-[.18em] text-lime-300">{badge}</p><h2 className="mt-4 text-2xl font-black">{title}</h2><p className="mb-7 mt-2 text-sm text-zinc-500">{label}</p>{children}</section>}
function NumberBox({label,value,setValue}:{label:string;value:string;setValue:(v:string)=>void}){return <label className="text-xs font-bold text-zinc-500">{label}<input value={value} onChange={e=>setValue(e.target.value)} type="number" min="0" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-xl font-black text-white outline-none"/></label>}
function Result({value,copy}:{value:string;copy:string}){return <div className="mt-5 border-t border-white/8 pt-5"><strong className="text-xl text-lime-300">{value}</strong><p className="mt-2 text-xs leading-5 text-zinc-500">{copy}</p></div>}
