import { PageIntro, SiteShell } from "@/components/SiteShell";

const guides = [
  { tag:"START HERE", read:"7 min", title:"How to build a balanced college list", copy:"A simple reach, target and likely framework that keeps ambition without betting everything on chance." },
  { tag:"ACADEMICS", read:"6 min", title:"What your GPA actually tells colleges", copy:"Understand course rigor, grade trends and why one number never tells the entire academic story." },
  { tag:"TESTING", read:"5 min", title:"Is your SAT score worth submitting?", copy:"A practical way to evaluate your score against a college’s typical admitted-student range." },
  { tag:"STRATEGY", read:"8 min", title:"Reach, target and likely: the honest version", copy:"Why acceptance rate alone can mislead you—and what to consider instead." },
  { tag:"APPLICATIONS", read:"9 min", title:"Your senior-year application timeline", copy:"A month-by-month map from final college research to decisions and deposits." },
  { tag:"COST", read:"7 min", title:"Sticker price is not your real college cost", copy:"Learn how grants, scholarships and residency can change what a school actually costs." },
];
export default function GuidesPage(){return <SiteShell><main className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><PageIntro eyebrow="Admissions guides" title="Less noise. Better next steps." copy="Clear, student-friendly explainers for the decisions between building a list and choosing a campus."/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{guides.map((g,i)=><article key={g.title} className={`group flex min-h-72 flex-col rounded-3xl border p-7 ${i===0?"border-lime-300/25 bg-lime-300/[.07]":"border-white/10 bg-white/[.03]"}`}><div className="flex items-center justify-between text-[10px] font-black tracking-wider"><span className="text-lime-300">{g.tag}</span><span className="text-zinc-600">{g.read}</span></div><h2 className="mt-auto text-2xl font-black leading-tight tracking-[-.035em]">{g.title}</h2><p className="mt-3 text-sm leading-6 text-zinc-400">{g.copy}</p><p className="mt-5 text-xs font-black text-white group-hover:text-lime-300">Coming soon →</p></article>)}</div><div className="mt-14 rounded-3xl border border-white/10 bg-[linear-gradient(120deg,rgba(190,242,100,.12),transparent_60%)] p-8 sm:flex sm:items-center sm:justify-between"><div><h2 className="text-2xl font-black">Know your numbers?</h2><p className="mt-2 text-sm text-zinc-400">Turn the advice into a quick, shareable chance check.</p></div><a href="/calculator" className="mt-6 inline-block rounded-full bg-lime-300 px-6 py-3 text-xs font-black text-zinc-950 sm:mt-0">Try the calculator →</a></div></main></SiteShell>}
