import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { universities } from "@/data/universities";
import { AdsterraAd } from "@/components/AdsterraAd";
import { InlineChanceCalculator } from "@/components/InlineChanceCalculator";
import { SiteShell } from "@/components/SiteShell";
import { HarvardSeoContent } from "@/components/HarvardSeoContent";

export function generateStaticParams() { return universities.map(u => ({ id: u.id })); }

export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params; const u = universities.find(x => x.id === id);
  if (!u) return {};
  if (u.id === "harvard") return { title: "Harvard Acceptance Calculator: GPA, SAT & Admission Chances", description: "Estimate your Harvard admission chances and learn the latest Harvard GPA profile, SAT requirements, score ranges, and application expectations.", alternates: { canonical: "/colleges/harvard" } };
  return { title: `${u.name} Acceptance Chance Calculator`, description: `Estimate your chances at ${u.name}. Explore GPA and SAT benchmarks, acceptance rate, similar colleges and admissions FAQs.`, alternates: { canonical: `/colleges/${u.id}` } };
}

export default async function CollegePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const u = universities.find(x => x.id === id); if (!u) notFound();
  const gpaLow = Math.max(3, u.avgGpa - .15).toFixed(2), gpaHigh = Math.min(4, u.avgGpa + .08).toFixed(2);
  const satLow = Math.max(900, u.avgSat - 70), satHigh = Math.min(1600, u.avgSat + 60);
  const similar = universities.filter(x => x.id !== u.id).sort((a,b) => Math.abs(a.prestige-u.prestige)-Math.abs(b.prestige-u.prestige)).slice(0,3);
  const selectivity = u.acceptanceRate < 10 ? "extremely selective" : u.acceptanceRate < 25 ? "highly selective" : u.acceptanceRate < 50 ? "selective" : "broadly accessible";
  const faqs = [
    [`Is ${u.name} a reach, target or likely school?`, `That depends on your complete profile. With a recent admit rate around ${u.acceptanceRate}%, ${u.name} is ${selectivity}. Admitly treats the label as a planning category, never a guarantee.`],
    [`What GPA do you need for ${u.name}?`, `A useful planning benchmark is roughly ${gpaLow}–${gpaHigh}, centered near ${u.avgGpa}. Course rigor, grade trend and school context matter alongside GPA.`],
    [u.testBlind ? `Does ${u.name} consider SAT scores?` : `Is a ${u.avgSat} SAT good for ${u.name}?`, u.testBlind ? `${u.name} is part of the University of California system, which does not use SAT or ACT scores in admission decisions.` : `${u.avgSat} is around the planning midpoint shown here. A score near ${satHigh} may strengthen the academic picture, but no score guarantees admission.`],
    [`How accurate is this ${u.name} calculator?`, `It is a playful planning estimate based on limited academic inputs. Essays, activities, recommendations, residency, major and institutional priorities are not modeled.`],
  ];
  return <SiteShell><main>
    <section className="border-b border-white/8 bg-[radial-gradient(circle_at_70%_0%,rgba(190,242,100,.08),transparent_35%)]"><div className="mx-auto max-w-6xl px-5 py-14 sm:px-8 sm:py-20"><nav className="text-xs font-bold text-zinc-600"><a href="/colleges" className="hover:text-white">Colleges</a> <span className="px-2">/</span> {u.name}</nav><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-xl text-sm font-black text-zinc-950" style={{backgroundColor:u.accent}}>{u.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] font-black uppercase text-zinc-500">{u.type}</span></div><h1 className="mt-7 max-w-4xl text-4xl font-black leading-[.94] tracking-[-.055em] sm:text-6xl">Can you get into <span className="text-lime-300">{u.name}?</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-zinc-400">Use the {u.name} acceptance chance calculator, review recent academic benchmarks and build a smarter college list.</p></div><a href="#calculator" className="rounded-full bg-lime-300 px-6 py-4 text-center text-sm font-black text-zinc-950">Calculate my chances ↓</a></div></div></section>
    <div className="mx-auto grid max-w-6xl gap-10 px-5 py-12 sm:px-8 lg:grid-cols-[1fr_20rem]"><article><section><p className="text-xs font-black uppercase tracking-[.2em] text-lime-300">Admissions snapshot</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat label="Admit rate" value={`${u.acceptanceRate}%`}/><Stat label="GPA benchmark" value={`${gpaLow}–${gpaHigh}`}/><Stat label={u.testBlind?"Testing":"SAT range"} value={u.testBlind?"Test-free":`${satLow}–${satHigh}`}/><Stat label="Undergraduates" value={u.enrollment}/></div><p className="mt-4 text-xs leading-5 text-zinc-600">Planning benchmarks compiled from recent publicly reported institutional figures. Admission data changes each cycle; verify current requirements with the university.</p></section><AdsterraAd format="native" className="my-8"/><InlineChanceCalculator university={u}/><AdsterraAd format="mobile" className="my-8 sm:hidden"/>{u.id === "harvard" && <HarvardSeoContent/>}<section className="mt-14"><p className="text-xs font-black uppercase tracking-[.2em] text-lime-300">How to read your result</p><h2 className="mt-3 text-3xl font-black tracking-tight">Reach, target or likely?</h2><div className="mt-6 grid gap-3 sm:grid-cols-3"><Tier name="Reach" range="Below 30%" copy="Possible, but build more options around it."/><Tier name="Target" range="30–69%" copy="Your academics are in the conversation."/><Tier name="Likely" range="70%+" copy="Promising—not guaranteed. Keep it sharp."/></div></section><section className="mt-14"><p className="text-xs font-black uppercase tracking-[.2em] text-lime-300">Keep exploring</p><h2 className="mt-3 text-3xl font-black">Colleges similar to {u.name}</h2><div className="mt-6 grid gap-3 sm:grid-cols-3">{similar.map(x=><a key={x.id} href={`/colleges/${x.id}`} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 hover:border-lime-300/30"><span className="text-[10px] font-black text-lime-300">{x.acceptanceRate}% ADMIT RATE</span><h3 className="mt-4 font-black">{x.name}</h3><p className="mt-1 text-xs text-zinc-500">{x.location}</p></a>)}</div></section><section className="mt-14"><p className="text-xs font-black uppercase tracking-[.2em] text-lime-300">Frequently asked</p><h2 className="mt-3 text-3xl font-black">{u.name} admissions FAQ</h2><div className="mt-6 divide-y divide-white/10 border-y border-white/10">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="cursor-pointer list-none pr-6 font-black">{q}<span className="float-right text-lime-300">+</span></summary><p className="mt-3 max-w-3xl text-sm leading-6 text-zinc-400">{a}</p></details>)}</div></section></article>
      <aside className="h-fit lg:sticky lg:top-24"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-[10px] font-black uppercase tracking-wider text-zinc-600">At a glance</p><dl className="mt-4 space-y-4 text-sm"><Side label="Location" value={u.location}/><Side label="Type" value={u.type}/><Side label="Tuition reference" value={`$${u.tuition.toLocaleString()}`}/><Side label="Selectivity" value={selectivity}/></dl><a href="/compare" className="mt-6 block rounded-full border border-white/15 px-4 py-3 text-center text-xs font-black">Compare this college →</a></div><AdsterraAd format="rectangle" className="mt-8 hidden lg:block"/></aside>
    </div>
  </main></SiteShell>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-[10px] font-black uppercase text-zinc-600">{label}</p><p className="mt-2 text-xl font-black">{value}</p></div>}
function Tier({name,range,copy}:{name:string;range:string;copy:string}){return <div className="rounded-2xl border border-white/10 p-5"><p className="text-xs font-black text-lime-300">{range}</p><h3 className="mt-2 text-xl font-black">{name}</h3><p className="mt-2 text-xs leading-5 text-zinc-500">{copy}</p></div>}
function Side({label,value}:{label:string;value:string}){return <div><dt className="text-[10px] uppercase text-zinc-600">{label}</dt><dd className="mt-1 font-bold capitalize text-zinc-300">{value}</dd></div>}
