import type { Metadata } from "next";
import { AdsterraAd } from "@/components/AdsterraAd";
import { SiteShell } from "@/components/SiteShell";

export const metadata: Metadata = { title: "What Colleges Can I Get Into? Find Matches by GPA and SAT", description: "Find colleges you may be able to get into using GPA, SAT score, admission ranges, cost, and fit.", alternates: { canonical: "/guides/what-colleges-can-i-get-into" } };

const sections = [
  ["Start with your academic profile", "Record your unweighted GPA, weighted GPA if available, recent course rigor, grade trend, SAT or ACT score, and intended major. GPA alone is difficult to compare because high schools use different scales. Colleges often review the transcript and school profile to understand which courses were offered and how you performed within that environment.", "Testing can provide another reference when a college considers scores. Confirm whether each institution is test-required, test-optional, or test-blind for your application cycle. A strong score may expand your apparent options, but it does not override years of coursework or guarantee admission."],
  ["Compare yourself with official ranges", "Look for the college’s recent first-year profile or Common Data Set. Compare your GPA and submitted test scores with the middle 50 percent range. Being near the midpoint suggests academic alignment, while being below the lower quartile may make the school more ambitious. Being above the upper quartile can strengthen your position but does not make an extremely selective college safe.", "Use data from the university whenever possible and note the year. Third-party averages can be outdated or calculated differently. For direct-admit and capacity-limited programs such as nursing, engineering, computer science, business, or arts, search for program-specific expectations and portfolio or audition requirements."],
  ["Create reach, target, and likely groups", "A reach is possible but unpredictable because of selectivity, academic distance, or program competition. A target broadly matches your profile and has a reasonably predictable selection process. A likely school appears favorable academically and admits a meaningful share of comparable applicants. Highly selective universities remain reaches for nearly everyone.", "Start with several colleges in each category rather than trusting one result. Every likely school should be somewhere you would genuinely attend. Every target should be researched beyond the numbers. Reaches should earn the additional application effort because they fit your goals—not simply because their names are famous."],
  ["Add location, major, and campus fit", "Admission is only useful if the college supports the experience you want. Filter by intended major, class size, location, campus environment, academic flexibility, internship access, housing, support, and distance from home. Separate must-haves from preferences so you can remove schools that look impressive but fail your actual needs.", "Students who are undecided should investigate how easily they can explore or change majors. Students pursuing specialized fields should confirm accreditation, progression standards, and whether admission is to the university or directly to the program. These details can matter more than a small difference in ranking."],
  ["Ask which colleges you can afford", "Run the official net price calculator for every serious option. Sticker price is not the same as net price after grants and scholarships. Include at least one financial safety that appears affordable under conservative assumptions. Do not treat competitive scholarships, future residency, or large private loans as guaranteed solutions.", "Compare estimated four-year costs, renewal requirements, transportation, and likely borrowing. A school can be an academic likely and a financial reach. Your final list should create multiple outcomes that work academically, personally, and financially."],
  ["Use a calculator as a starting point", "A college acceptance calculator can rapidly compare your GPA and SAT with broad benchmarks across many institutions. Use it to discover possibilities and identify where more research is needed. Do not use the percentage as a promise or rejection. Essays, recommendations, activities, course rigor, context, major, and institutional priorities remain outside simple models.", "Try the free Admitly college acceptance calculator, save promising schools, and verify every requirement on official websites. Then pressure-test the list with a counselor, educator, or trusted adult who understands your school context."],
  ["A practical final checklist", "Aim for a manageable list you can complete well. Confirm deadlines, application plans, supplements, recommendation requirements, testing rules, financial aid forms, and program details. Remove any college you would not attend over your other options. Add choices when one category depends on several highly uncertain decisions.", "The question “what colleges can I get into?” becomes more useful when it changes to “which colleges give me several realistic, affordable ways to succeed?” Your numbers help define the search, but your priorities determine which results deserve a place on the list."],
] as const;

export default function WhatCollegesGuide(){return <SiteShell><main><header className="border-b border-white/8 bg-[radial-gradient(circle_at_70%_0%,rgba(190,242,100,.08),transparent_38%)]"><div className="mx-auto max-w-4xl px-5 py-16 sm:px-8 sm:py-20"><p className="text-xs font-black uppercase tracking-[.22em] text-lime-300">College matching · 9 min</p><h1 className="mt-4 text-4xl font-black leading-[.98] tracking-[-.055em] sm:text-6xl">What colleges can I get into?</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-zinc-400">Use your GPA, SAT score, academic context, preferences, and budget to build a realistic list of colleges where you could thrive.</p></div></header><article className="mx-auto max-w-4xl px-5 py-12 text-[1.03rem] leading-8 text-zinc-300 sm:px-8"><p className="text-xl leading-9 text-zinc-200">The honest answer is not a single list generated from one score. Colleges evaluate academic preparation in context, and admission difficulty changes by institution, program, residency, and applicant pool. Still, you can use reliable benchmarks to identify schools that appear likely, realistic, or ambitious. This process starts with your transcript and testing, then adds selectivity, affordability, and personal fit.</p>{sections.map(([heading,p1,p2],index)=><section key={heading} className="mt-12"><h2 className="text-3xl font-black tracking-tight text-white">{heading}</h2><p className="mt-5">{p1}</p><p className="mt-5">{p2}{index===5&&<> <a href="/calculator" className="font-bold text-lime-300">Try the calculator now.</a></>}</p>{index===1&&<AdsterraAd format="native" className="my-10"/>}{index===4&&<AdsterraAd format="rectangle" className="my-10"/>}</section>)}</article></main></SiteShell>}
